global:
  scrape_interval: "15s"  # 모든 타겟에서 메트릭을 수집하는 주기를 15초로 설정
  evaluation_interval: "15s"  # 알림 규칙을 평가하는 주기를 15초로 설정

scrape_configs:
  - job_name: "springboot"  # Spring Boot 애플리케이션 메트릭 수집을 위한 작업 이름
    metrics_path: "/monitor/prometheus"  # Spring Boot의 Prometheus 메트릭 경로
    static_configs:
      - targets:
          - "host.docker.internal:8080"  # 메트릭을 수집할 Spring Boot 애플리케이션의 주소 및 포트
    scrape_interval: 1s

  - job_name: "prometheus"  # Prometheus 서버 메트릭 수집을 위한 작업 이름
    static_configs:
      - targets:
          - "host.docker.internal:9090"  # Prometheus 서버의 주소 및 포트

